# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 313bcab1b1b42fef2bd0175d44bdddde54a0aa9879465e49e56013d475d5d54483b605bf9d0c1d778e651ceb3e182ac3811be3d8d9aa241cfb474704c1171cb3

test:
  secret_key_base: 5fbfad4c909d96f61491cc09257fff995f0251418f0380a8327741475dd5ff8d02f2fe7242add048cc3c589d8c04ce6dc77f16e3b032080b92da24cd3c991668

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
